---
- name: Front Playbook
  hosts: all  
  gather_facts: yes
  become: yes  
  vars:
    IMG: "connectify-front-dev"
    TAG: "latest"
  tasks:

    - name: PING | The Linux VMs
      ansible.builtin.ping:

    - name: ENV | Setup
      set_fact:
        env_secrets: "{{ lookup('env', 'FRONTEND_SECRETS') | from_json }}"

    - name: DOCKER | Configure Docker credentials
      community.docker.docker_login:
        registry_url: "{{env_secrets.REGISTRY}}"
        username: "{{env_secrets.USERNAME}}"
        password: "{{env_secrets.PASSWORD}}"
        reauthorize: true

    - name: DOCKER | Pull - FRONTEND
      community.docker.docker_image:
        name: "{{env_secrets.REGISTRY}}/{{IMG}}"
        source: pull
        tag: "{{TAG}}"


    - name: DOCKER | Recreate - FRONTEND
      community.docker.docker_container:
        name: react
        image: "{{env_secrets.REGISTRY}}/{{IMG}}:{{TAG}}"
        env:
          REACT_APP_BASE_URL: "{{env_secrets.REACT_APP_BASE_URL}}"
          REACT_APP_BLOB_STORAGE_BASE_URL: "{{env_secrets.REACT_APP_BLOB_STORAGE_BASE_URL}}"
          REACT_APP_BLOB_STORAGE_EVENT_IMAGES: "{{env_secrets.REACT_APP_BLOB_STORAGE_EVENT_IMAGES}}"
          REACT_APP_BLOB_STORAGE_GALLERY_IMAGES: "{{env_secrets.REACT_APP_BLOB_STORAGE_GALLERY_IMAGES}}"
        state: started
        recreate: true
        restart_policy: unless-stopped
        container_default_behavior: compatibility
        ports:
          - "80:80"