---
- name: Azure Virtual Machine
  hosts: env_DEV
  gather_facts: yes
  become: yes
  vars:
    acr: "atcdevacr.azurecr.io"
    front:
      image: "connectify-front-dev_test"
      tag: "latest"

  tasks:

    - name: PING | The Linux VMs
      ansible.builtin.ping:

    - name: Configure Docker credentials
      community.docker.docker_login:
        registry_url: atcdevacr.azurecr.io
        username: {{ secrets.ACR_USERNAME }}
        password: {{ secrets.ACR_PASSWORD }}
        reauthorize: true

    - name: DOCKER | Pull the Front End Application image from Docker Hub
      community.docker.docker_image:
        name: "{{acr}}/{{front.image}}:{{front.tag}}"
        source: pull
        tag: latest

    - name: DOCKER | Run the Front End Application
      community.docker.docker_container:
        name: react-app
        image: "{{acr}}/{{front.image}}:{{front.tag}}"
        state: started
        restart_policy: unless-stopped
        container_default_behavior: compatibility
        ports:
          - "80:80"
