name: ANSIBLE | Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev_test" ]
  pull_request:
    branches: [ "dev_test" ]

  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python and Install Ansible
      - name: Set up Python and Install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # # Step 3: Run Ansible Playbook
      # - name: Run Ansible Playbook
      #   run: |
      #     ansible-playbook -i inventory.yml playbook.yml

