
name: Ansible Deployment

on:
  push:
    branches: [ "dev_test" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      DATABASE_SECRETS: ${{ secrets.DATABASE_SECRETS }}
      BACKEND_SECRETS: ${{ secrets.BACKEND_SECRETS }}
      FRONTEND_SECRETS: ${{ secrets.FRONTEND_SECRETS }}
    steps:

      - name: GIT | Checkout
        uses: actions/checkout@v4

      - name: SETUP | Key Pair
        run: |
          mkdir key_pairs
          echo "${{ secrets.KP }}" > connectify_kp.pem
          sudo chmod 600 connectify_kp.pem

      - name: Python | Install
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ansible | Setup Output
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'  # Only run this for PR events
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require("fs");
            const output = fs.readFileSync("/tmp/ansible_output.txt", "utf8");
            const maxGitHubBodyCharacters = 65536;  # Maximum size for GitHub comments

            // Function to split output into smaller chunks if it's too large
            function chunkSubstr(str, size) {
              const numChunks = Math.ceil(str.length / size);
              const chunks = new Array(numChunks);
              for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
                chunks[i] = str.substr(o, size);
              }
              return chunks;
            }

            var outputChunks = chunkSubstr(output, maxGitHubBodyCharacters);  // Split if needed
            for (let i = 0; i < outputChunks.length; i++) {
              const comment = `### Ansible Playbook Output - Part ${i + 1}
              <details><summary>Show Output</summary>
              \`\`\`
              ${outputChunks[i]}
              \`\`\`
              </details>`;
              
              // Post the comment on the PR
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
  

      - name: Ansible | Setup and Execute
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install ansible==10.7.0

          ansible-playbook frontend_playbook.yaml -i "${{secrets.HOST_VM}}," -e "ansible_user=${{secrets.ANSIBLE_USER}} ansible_ssh_private_key_file=.key_pairs/connectify_kp.pub"