
name: Ansible Deployment


on:
  push:
    branches: [ "dev_test" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    env:
      PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      VOC_KEY: ${{ secrets.VOC_KEY }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      ANSIBLE_USERs: "TEST"


    steps:

      - name: GIT | Checkout
        uses: actions/checkout@v3


      - name: SETUP | Key Pair
        run: |
          mkdir key_pairs
          echo "${{ secrets.KP }}" > connectify_kp.pem
          sudo chmod 600 connectify_kp.pem

      - name: Python | Install
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ansible | Setup
        run: |
          python -m pip install --upgrade pip
          pip install ansible==10.7.0
          ansible-galaxy collection install azure.azcollection:2.7.0 --force

          ansible --version
          ansible-galaxy collection list | grep azure.azcollection

          ansible-inventory -i ./atc_azure_rm.yaml --graph

